# Site settings
title: ANZ Coders
email: admin@anzcoders.com
description: "Virtual conference for Australian and New Zealand software developers"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: ANZ Coders
  location: Location
  social: Contact Us
  credits: Theme

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/anzcoders
  - title: facebook
    url:
  - title: youtube
    url: http://youtube.com/anzcoders
  - title: envelope-o
    url: mailto:contact@anzcoders.com

# Postal address (add as many lines as necessary)
address:
  - line: On a screen near you.
  - line: Your place. Your device.
  
# Credits content
credits: 'Freelance Theme courtesy of <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
